import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="dark">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {children}
      </body>
    </html>
  );
}

// // app/(app)/layout.tsx
// 'use client';

// import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
// import { httpBatchLink } from '@trpc/client';
// import { useState } from 'react';
// import { trpc } from '@/lib/trpc/trpc.client';
// import superjson from 'superjson';

// export default function AppLayout({ children }: { children: React.ReactNode }) {
//   const [queryClient] = useState(() => new QueryClient());

//   const [trpcClient] = useState(() =>
//     trpc.createClient({
//       transformer: superjson,
//       links: [
//         httpBatchLink({
//           url: '/api/trpc',
//         }),
//       ],
//     })
//   );

//   return (
//     <trpc.Provider client={trpcClient} queryClient={queryClient}>
//       <QueryClientProvider client={queryClient}>
//         {children}
//       </QueryClientProvider>
//     </trpc.Provider>
//   );
// }